// source: test_cadquery.py::TestCadQuery::testSketch (var r1)
// r1 = Workplane().box(10,10,1).faces(">Z").sketch()
//        .slot(2,1).slot(2,1,angle=90).clean().finalize().extrude(1)
// ref anchor: bbox z[-0.5,1.5], topo f19/e48/v32 (crossing slots on the top face)
import * as cq from '@faicad/cq-compat'
let base = await cq.box(cq.Workplane(), 10, 10, 1)
let fz = await cq.faces(base, '>Z')
let topWp = await cq.workplane(fz)
let sk0 = cq.sketch(topWp)
let sk1 = cq.sketchSlot(sk0, 2, 1)
let sk2 = cq.sketchSlot(sk1, 2, 1, { angle: 90 })
let sk3 = cq.sketchClean(sk2)
let wp = cq.sketchFinish(sk3, topWp)
let r1 = await cq.extrude(wp, 1)
let result = cq.val(r1)
