// source: test_cadquery.py::TestCadQuery::testQuickStartXZ (var s)
// s = Workplane(Plane.XZ()).box(2,4,0.5).faces(">Y").workplane()
//       .rect(1.5,3.5,forConstruction=True).vertices().cskHole(0.125,0.25,82,depth=None)
import * as cq from '@faicad/cq-compat'
let base = await cq.box(cq.Workplane('XZ'), 2, 4, 0.5)
let topFace = await cq.faces(base, '>Y')
let wp = await cq.workplane(topFace)
let r = cq.rect(wp, 1.5, 3.5, { forConstruction: true })
let v = cq.vertices(r)
let s = await cq.cskHole(v, 0.125, 0.25, 82)
let result = cq.val(s)
